config/routes.rb
Rails.application.routes.draw do
  get("/", { :controller => "places", :action => "index" })
  resources "entries"
  resources "places"
  resources "sessions"
  resources "users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    puts "------------------ code before every request ------------------"
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def new
  end

  def create
    @entry = Entry.new
    @entry["title"] = params["title"]
    @entry["description"] = params["description"]
    @entry["occurred_on"] = params["occurred_on"]
    @entry["place_id"] = params["place_id"]
    @entry["user_id"] = session["user_id"]
    @entry.save
    redirect_to "/places/#{@entry["place_id"]}"
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find_by({ "id" => params["id"] })
    
    @entries = Entry.where({ "place_id" => @place["id"], "user_id" => session["user_id"] })
  end

  def new
  end

  def create
    @place = Place.new
    @place["name"] = params["name"]
    @place.save
    redirect_to "/places"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by({ "email" => params["email"] })
    if @user != nil
      if BCrypt::Password.new(@user["password"]) == params["password"]
        session["user_id"] = @user["id"]
        flash["notice"] = "You are now logged-in."
        redirect_to "/"
      else
        flash["notice"] = "Sorry, invalid username or password."
        redirect_to "/login"
      end
    else
      flash["notice"] = "Sorry, invalid username or password."
      redirect_to "/login"
    end
  end

  def destroy
    session["user_id"] = nil
    flash["notice"] = "Goodbye."
    redirect_to "/login"
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new
    @user["first_name"] = params["first_name"]
    @user["last_name"] = params["last_name"]
    @user["username"] = params["username"]
    @user["email"] = params["email"]
    @user["password"] = BCrypt::Password.create(params["password"])
  
    @user.save
    redirect_to "/places"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<div class= "container">


<h1>New Entry</h1>

  <form action="/entries" method="post">
    <input type="hidden" name="place_id" value="<%= params["place_id"] %>">

    <div class="mb-3">
      <label for="title_input" class="form-label">Title</label>
      <input type="text" name="title" id="title_input" class="form-control">
    </div>

    <div class="mb-3">
      <label for="description_input" class="form-label">Description</label>
      <input type="text" name="description" id="description_input" class="form-control">
    </div>

    <div class="mb-3">
      <label for="occurred_on_input" class="form-label">Occurred On</label>
      <input type="date" name="occurred_on" id="occurred_on_input" class="form-control">
    </div>

    <button type="submit" class="btn btn-secondary">Save</button>
  </form>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <% if session["user_id"] %>
      <% user = User.find_by(id: session["user_id"]) %>
      <a class="navbar-brand" href="/">Hi, <%= user.first_name if user %>!</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if session["user_id"] == nil %>
          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/new">Signup</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tacostagram Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="/stylesheets/application.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

 <body>
  <%= render 'layouts/header'%>

<% if flash["notice"].present? %>

    <div class="alert alert-success py-2 mb-0" role="alert">
      <%= flash["notice"] %>
    </div>
  <% end %>

    <%= yield %>
  </body>
</html>

</html>

app/views/places/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Places</h1>
  <div class="row">
    <% @places.each do |place| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= link_to place["name"], place_path(place["id"]), class: "stretched-link" %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="text-center mt-4">
    <%= link_to 'Add New Place', new_place_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<form action="/places" method="post">
  <p>
    <label for="name_input">Name</label>
    <input type="text" name="name" id="name_input">
  </p>

  <button>Save</button>
</form>

app/views/places/show.html.erb
<div class="container">



  <h1><%= @place["name"] %></h1>


  <h2>My Entries</h2>
  <% for entry in @entries %>


    <div class="card mb-3">
      <div class="card-body">
        <h3 class="card-title"><%= entry["title"] %></h3>
        <h4 class="card-subtitle mb-2 text-muted"><%= entry["occurred_on"] %></h4>
        <p class="card-text"><%= entry["description"] %></p>
        <p class="card-text"><%= entry["user_id"] %></p>
      </div>
    </div>
    
  <% end %>

  <p>
    <% if session["user_id"] %>
      <a href="/entries/new?place_id=<%= @place["id"] %>" class="btn btn-secondary">New Entry</a>
    <% end %>
  </p>

  <p>
    <a href="/places" class="btn btn-secondary">Back to All Places</a>
  </p>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>New User Account</h1>

  <form action="/users" method="post">
    <div class="mb-3">
      <label for="first_name" class="form-label">First Name</label>
      <input type="text" name="first_name" id="first_name" class="form-control">
    </div>
    <div class="mb-3">
      <label for="last_name" class="form-label">Last Name</label>
      <input type="text" name="last_name" id="last_name" class="form-control">
    </div>
    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input type="text" name="username" id="username" class="form-control">
    </div>
    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input type="text" name="email" id="email" class="form-control">
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" name="password" id="password" class="form-control">
    </div>
    <button type="submit" class="btn btn-secondary">Signup</button>
  </form>
</div>